### ISSUE TITLE
Varnish cacheable requests

### ISSUE THREAD

**Issue by MO-BrandonR** [tessera-metrics/tessera#351]
We have varnish in front of our Graphite's web server as we are trying to keep the impact to the server low.  A lot of the render requests end in jsonp=jQuery<numbers>_<numbers>=<numbers> which causes the requests to bypass the cache.  I did some testing and was pulling the same data whether the numbers were appended or not.  Here's an example call:

Request URL:http://<graphite_url>//render?format=json&from=-1h&tz=Etc%2FUTC&target=<query>&jsonp=jQuery1110006516687339171767_1419377088900&_=1419377088901

Are these necessary for something?  Is there a way to disable this?  Maybe make it a configuration option?

Regards,
Brandon

**Comment by aalpern** [comment]
@MO-BrandonR This is an artifact of the jsonp format support in jQuery used for handling graphite authentication. I'll see about disabling it when auth is not needed, and whether it's really necessary or not when using auth. Sorry for the delay! Not much happened over the holidays :)

**Comment by MO-BrandonR** [comment]
No worries.  Thanks for the update and the awesome dashboard!

**Comment by aalpern** [comment]
After the switch to `axios` for making graphite requests, this should no longer be an issue.
