### ISSUE TITLE
Instrument Query for loading times

### ISSUE THREAD

**Issue by aalpern** [tessera-metrics/tessera#370]
Another old idea from @bitprophet, from discussions back in tessera's infancy: if we instrument the loading of graphite queries, we could optionally display information on how much cumulative time a dashboard takes talking to graphite. This can be used to display and rank dashboards by how expensive they are (and possibly discourage people from building the kind of dashboard that throws hundreds of every possible metric from a given service on a single page). 

With marks and measures from the `window.performance` API, this is pretty straightforward. 
- Instrument `ds.models.data.Query` to mark start/end times
- Record the measure between them
- Add a panel to the dashboard page which can be opened from the toolbar to display query times (and anything else we want to instrument - rendering time would be another one)
- Optionally store most recent load times in a dashboard's metadata, so we can indicate it in the dashboard list

**Comment by barthoda** [comment]
We had a requirement for this, so we turned to New Relic Browser Monitoring. It does very similar stuff to what you're saying. Then we use New Relic APM to optimise graphite.

Not trying to be a New Relic ad.

**Comment by bitprophet** [comment]
:+1: to storing the results in metadata - maybe even a ring buffer to calculate an average over the last, like, dozen loads or whatever.

**Comment by aalpern** [comment]
This turns out to be pretty easy with the new user-timing API. Work started in this branch - https://github.com/urbanairship/tessera/tree/issue-370-instrumentation

**Comment by aalpern** [comment]
Instrumentation is checked in (although it has some limitations due to asynchronous processing). I'm going to leave this open until there's a way to expose it.
