### ISSUE TITLE
Some dashboards stopped working after upgrading to 0.8.1

### ISSUE THREAD

**Issue by deejay1** [tessera-metrics/tessera#508]
After upgrading to 0.8.1 some dashboards stopped working returning an HTTP 500 error. It seems to be a ValueError "Invalid control character at: line 56 column 100 (char 1352)"

``` python

  File "flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "tessera/views_api.py", line 35, in wrapper
    value = fn(*args, **kwargs)
  File "tessera/views_api.py", line 178, in dashboard_get
    dash = _set_dashboard_hrefs(dashboard.to_json(rendering or include_definition))
  File "tessera/database.py", line 64, in to_json
    data['definition'] = json.loads(self.definition.definition)
  File "json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
```

The main culprit seem to be "\n" characters in definition['queries'][*]['targets'].
Temporary workaround was to add replace['\n',''] to tessera/database.py", line 64

**Comment by aalpern** [comment]
2015, and still we're plagued by encoding of line endings. This is how the world ends. Not in fire. Not in ice. In text encoding.

**Comment by aalpern** [comment]
@deejay1 Can you include some platform information? 

* What browser on what OS on the client side
* What OS you're running on the server side

**Comment by aalpern** [comment]
Also what Python version, please. Tessera is most thoroughly tested in Python 2.7.

**Comment by deejay1** [comment]
Client: latest Firefox/Chrome, systems OSX + Linux
Server: Ubuntu 12.04 Python 2.7.3
installed modules:
```
alembic (0.8.2)
apt-xapian-index (0.44)
blinker (1.4)
boto (2.2.2)
carbonate (0.2.2)
chardet (2.0.1)
Cheetah (2.4.4)
cloud-init (0.6.3)
command-not-found (0.2.44)
configobj (4.7.2)
diamond (4.0.89)
distribute (0.7.3)
Django (1.7.4)
django-tagging (0.3.4)
euca2ools (2.0.0)
Flask (0.10.1)
Flask-Cors (2.0.1)
Flask-Migrate (1.2.0)
Flask-Script (2.0.5)
Flask-SQLAlchemy (1.0)
freeipa (2.0.0a0)
gevent (0.13.6)
GnuPGInterface (0.3.2)
greenlet (0.3.1)
inflection (0.2.0)
ipapython (2.1.4)
itsdangerous (0.24)
Jinja2 (2.8)
JPype (0.5.4.2)
kerberos (1.0)
language-selector (0.1)
lxml (2.3.2)
M2Crypto (0.21.1)
maas-sdp (0.0.9)
Mako (1.0.2)
MarkupSafe (0.23)
meld3 (1.0.2)
mod-python (3.3.1)
MySQL-python (1.2.3)
netaddr (0.7.5)
oauth (1.0.1)
PAM (0.4.2)
paramiko (1.7.7.1)
pip (6.0.8)
psycopg2 (2.4.5)
pycrypto (2.4.1)
pycurl (7.19.0)
pyOpenSSL (0.12)
pyserial (2.5)
python-apt (0.8.3ubuntu7.1)
python-debian (0.1.21ubuntu1)
python-default-encoding (0.1)
python-editor (0.4)
python-ldap (2.3.13)
python-nss (0.12)
pytz (2014.10)
PyYAML (3.10)
raven (5.6.0)
requests (2.4.3)
setuptools (18.2)
simplejson (3.5.2)
six (1.9.0)
SQLAlchemy (0.9.4)
supervisor (3.1.3)
tessera (0.8.1)
tessera-client (0.4.5)
Twisted (15.0.0)
Twisted-Core (11.1.0)
txAMQP (0.6.2)
ufw (0.31.1-1)
unattended-upgrades (0.1)
virtualenv (1.7.1.2)
Werkzeug (0.10.4)
whisper (0.9.13)
zope.interface (3.6.1)
```

**Comment by aalpern** [comment]
thanks!

**Comment by deejay1** [comment]
Some weird "test case" for this issue seem to be that dashboard.to_json seem to do the something along the lines of
```python
import json
json.loads('"\n"')
```
as the above gives exactly the same exception (+/1 character location of course) as the error reported by tessera.

**Comment by aalpern** [comment]
Yeah, I see - control characters (i.e. `\n`) aren't allowed in string literals. They need to be escaped (`"\\n"`). Somewhere along the line it's either not getting escaped in your case, or behaving more leniently in my case. We have a _lot_ of queries with newlines in them in our production dashboards have never run into this before. Still investigating.

**Comment by aalpern** [comment]
@deejay1 You've got a **lot** of python modules loaded that aren't related to Tessera - it's possible one of them is causing the behavior you're seeing. Are you deploying tessera in the same virtual environment as other python applications, or have some custom integration in your version?

Here's the list of everything installed in a fresh tessera environment:

```
Flask==0.10.1
Flask-Cors==2.0.1
Flask-Migrate==1.2.0
Flask-SQLAlchemy==1.0
Flask-Script==2.0.5
Jinja2==2.8
Mako==1.0.2
MarkupSafe==0.23
SQLAlchemy==0.9.4
Werkzeug==0.10.4
alembic==0.8.2
inflection==0.2.0
itsdangerous==0.24
python-editor==0.4
requests==2.4.3
six==1.9.0
tessera-client==0.4.5
wsgiref==0.1.2
```

**Comment by deejay1** [comment]
Yeah, I've noticed yesterday that my predecessors installed it with  system site packages. I'll try to isolate it on Monday/Tuesday when I get back to work, but I fear it won't help much.
Also we'll try to anonimise/prettify the dashboard then as right now it's a couple thousand characters as a single line in the DB which isn't easy to read. Funny thing is that it broke on the upgrade (although I will test it again myself and try not to hurt someone if it comes out that it was broken before and they just said it broke after the upgrade....)

**Comment by deejay1** [comment]
OK, ignore this issue - things were broken on 0.7.x already only the users noticed it after the upgrade when we asked them to check their dashboards....

**Comment by aalpern** [comment]
Thanks for the update! I've still been unable to reproduce.
