### ISSUE TITLE
pip need requests version must be 2.12.3 

### ISSUE THREAD

**Issue by qq98982** [tessera-metrics/tessera#545]
Using pip3 install other package, it echos:
tessera 0.10.0 has requirement requests==2.12.3, but you'll have requests 2.18.4 which is incompatible.
after install requests2.12.3:
requestium 0.1.9 has requirement requests>=2.18.1, but you'll have requests 2.12.3 which is incompatible.

OS: Linux mint 18.3
Python version: 3.6.5
pip3 version: 10.0.1
tessera version: 0.10.0

**Comment by aalpern** [comment]
Yes, the versions are pinned to avoid unexpected breakage from dependency upgrades. You can only run into this problem if you're installing Tessera in a virtualenv that you're sharing with other projects - I recommend against doing that.

**Comment by qq98982** [comment]
Thanks for your answer, I wish it would have a better solution for it.

**Comment by aalpern** [comment]
My better solution is Golang :)
